[package]
name = "ludum_dare_56"
version = "0.1.0"
edition = "2021"

[dependencies]
leafwing-input-manager = "0.15"
avian2d = "0.1"

[dependencies.bevy]
version = "0.14"

[dependencies.bevy_egui]
version = "0.30"
